run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosimple
    - gosec
    - govet
    - ineffassign
    - intrange
    - errchkjson
    - forcetypeassert
    - misspell
    - nonamedreturns
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unused
    - errorlint
    - wrapcheck
